exp: 'default'
out_dir: 'exp'
seed: 0
num_train_steps: 200000
cg_iters: 10
hidden_dim: 32
model_hidden_dim: 32
batch_size: 256
init_steps: 1000
metric_warmup_steps: 5000
eval_frequency: 1000
log_frequency: 1000
model_log_frequency: 20000
num_Q_steps: 1 
num_T_steps: 1 # 1,3
num_ensemble_vep: 5
eps: 0.1
discount: 0.99
lr: 1e-3
inner_lr: 3e-4 
metric_lr: 1e-3 # 1e-3, 1e-4
weight_decay: 0.0 # 1e1, 1e-1, 1e-3
regularization_coeff: 0.0
alpha: 0.01
tau: 0.01
q_grad_clip: False
metric_grad_clip: False
metric_contional: False
with_inv_jac: False
with_inv_jac_model: True
save_buf: False
save_agent: False
hard: False
no_learn_reward: False
prob_model: False
no_warm: False
warm_opt: True
no_double: False
metric_activation: normalize # normalize, sigmoid, softplus
agent_type: 'omd'
env_name: 'CartPole-v1'
data_path: 'data/bu.pkl'
agent_path: 'data/agent.pkl'
dim_distract: 0 # 16, 32, 64, 128, 256, 512
use_wandb: True
wandb_project: 'metric-learning'
wandb_entity: 'theshank'
save_video: False