exp: 'default'
out_dir: 'exp'
seed: 0
num_train_steps: 200000
cg_iters: 10
hidden_dim: 32
model_hidden_dim: 32
batch_size: 256 # 256, 1024
init_steps: 1000
metric_warmup_steps: 5000
eval_frequency: 1000
log_frequency: 1000
num_Q_steps: 1 # 1,3
num_T_steps: 1
num_ensemble_vep: 5
eps: 0.1 # 0.05, 0.1
discount: 0.99
lr: 1e-3 # 1e-4, 1e-3
inner_lr: 3e-4 # 1e-4, 3e-4
metric_lr: 1e-3
alpha: 0.01 # 0.005, 0.01
tau: 0.01 #  0.005, 0.01, 1
q_grad_clip: False
metric_grad_clip: False
save_buf: False
save_agent: False
hard: False
no_learn_reward: False
prob_model: False
no_warm: False
warm_opt: False
no_double: False
with_inv_jac: False
with_inv_jac_model: False
agent_type: 'omd'
env_name: 'CartPole-v1'
data_path: 'data/bu.pkl'
agent_path: 'data/agent.pkl'
dim_distract: 0
use_wandb: True
wandb_project: 'metric-learning'
wandb_entity: 'theshank'
save_video: False