predictor_kwargs:
    num_layers: 1

problem_kwargs:
    num_train_instances: 400
    num_test_instances: 400
    num_items: 50
    budget: 1
    rand_seed: ${dataset_seed}
    val_frac: 0.5

taskmet_kwargs:
    batchsize: 50   
    inner:
        inner_lr: 0.1