# @package _global_

loss: 'metric'

loss_kwargs:
    dflalpha: 0.0

model_kwargs:
    prediction_batchsize: 10
    implicit_diff_batchsize: 50
    implicit_diff_mode: torchopt_normal_cg
    implicit_diff_iters: 5
    predictor_lr: ${pred_lr}
    # implicit_diff_mode: exact
    predictor_grad_norm_threshold: 1e-3
    predictor_grad_clip_norm: 1e-0

    metric_kwargs:
    #   version: 'v1'
      num_hidden: 200
      identity_init: False
      identity_init_scale: 100.

num_inner_iters_init: 5000
num_inner_iters: 100
