# @package _global_

loss: 'metric'

loss_kwargs:
    dflalpha: 0.0

model_kwargs:
    prediction_batchsize: 10
    implicit_diff_batchsize: 50
    implicit_diff_mode: torchopt_normal_cg
    implicit_diff_iters: 5
    predictor_lr: ${pred_lr}
    # implicit_diff_mode: exact

    metric_kwargs:
      num_hidden: 100
      identity_init: True
      identity_init_scale: 100.

num_inner_iters_init: 5000
num_inner_iters: 50
