defaults:
  - _self_
  - problem: cubic
  - method: mse
  - override hydra/launcher: submitit_slurm

loadnew: False
iters: 5000
earlystopping: False
patience: 100
valfreq: 100
seed: 0
pred_model: 'dense'
lr: 1e-4
batchsize: 1

model_kwargs: {}
loss_kwargs: {}

hydra:
  run:
    dir: ./exp/local/${now:%Y.%m.%d}/${now:%H%M}
  job:
    chdir: True
  sweep:
    dir: ./exp/${now:%Y.%m.%d}/${now:%H%M}
    subdir: ${hydra.job.num}
  launcher:
    max_num_timeout: 100000
    timeout_min: 4319
    partition: devlab
    mem_gb: 64
    gpus_per_node: 1
