defaults:
  - _self_
  - method: metric
  - problem: cubic
  - override hydra/launcher: submitit_slurm

loadnew: False
iters: 5000
patience: 100
valfreq: 50
seed: 0
dataset_seed: 0
pred_model: 'dense'
verbose: False

batchsize: ??
pred_lr: ??

model_kwargs: {}
loss_kwargs: {}

hydra:
  run:
    dir: ./exp/local/${now:%Y.%m.%d}/${now:%H%M}
  job:
    chdir: True
  sweep:
    dir: ./exp/${now:%Y.%m.%d}/${now:%H%M}
    subdir: ${hydra.job.num}_${hydra.runtime.choices.problem}_${hydra.runtime.choices.method}
  launcher:
    max_num_timeout: 100000
    timeout_min: 4319
    partition: learnlab
    mem_gb: 64
    gpus_per_node: 1
    
